// <author>QROST</author>

using System;
using System.Collections.Generic;
using Rhino;
using Rhino.DocObjects;
using Rhino.Geometry;
using MeshyRhino.Models;

namespace MeshyRhino.Services
{
    public static class MeshyImportService
    {
        /// <summary>
        /// Add the parsed mesh as a standalone mesh object in the document.
        /// Vertices are converted from meters (Meshy output) to the document's unit system.
        /// </summary>
        public static Guid PlaceAsMesh(RhinoDoc doc, ParsedMesh parsed, string texturePath = null)
        {
            var rhinoMesh = BuildRhinoMesh(parsed, doc.ModelUnitSystem);

            var attr = new ObjectAttributes { Name = parsed.Name ?? "Meshy_Model" };
            
            if (!string.IsNullOrEmpty(texturePath))
            {
                int matIndex = CreateTexturedMaterial(doc, parsed.Name ?? "Meshy_Material", texturePath);
                if (matIndex >= 0)
                {
                    attr.MaterialIndex = matIndex;
                    attr.MaterialSource = Rhino.DocObjects.ObjectMaterialSource.MaterialFromObject;
                }
            }

            var id = doc.Objects.AddMesh(rhinoMesh, attr);

            if (id == Guid.Empty)
                throw new InvalidOperationException("[Meshy Rhino] Failed to add mesh to document.");

            doc.Views.Redraw();
            return id;
        }

        public static Guid PlaceAsBlock(RhinoDoc doc, ParsedMesh parsed, string texturePath = null)
        {
            var rhinoMesh = BuildRhinoMesh(parsed, doc.ModelUnitSystem);

            string blockName = GenerateUniqueBlockName(doc, parsed.Name ?? "Meshy_Model");

            var meshAttr = new ObjectAttributes { Name = parsed.Name ?? "Meshy_Model" };
            
            if (!string.IsNullOrEmpty(texturePath))
            {
                int matIndex = CreateTexturedMaterial(doc, parsed.Name ?? "Meshy_Material", texturePath);
                if (matIndex >= 0)
                {
                    meshAttr.MaterialIndex = matIndex;
                    meshAttr.MaterialSource = Rhino.DocObjects.ObjectMaterialSource.MaterialFromObject;
                }
            }

            int defIndex = doc.InstanceDefinitions.Add(
                blockName,
                "Generated by Meshy AI",
                Point3d.Origin,
                new GeometryBase[] { rhinoMesh },
                new ObjectAttributes[] { meshAttr });

            if (defIndex < 0)
                throw new InvalidOperationException("[Meshy Rhino] Failed to create block definition.");

            var xform = Transform.Identity;
            var instanceId = doc.Objects.AddInstanceObject(defIndex, xform);

            if (instanceId == Guid.Empty)
                throw new InvalidOperationException("[Meshy Rhino] Failed to place block instance.");

            doc.Views.Redraw();
            return instanceId;
        }

        private static int CreateTexturedMaterial(RhinoDoc doc, string name, string texturePath)
        {
            var mat = new Rhino.DocObjects.Material
            {
                Name = name,
                DiffuseColor = System.Drawing.Color.White
            };
            
            mat.SetBitmapTexture(texturePath);
            
            return doc.Materials.Add(mat);
        }

        /// <summary>
        /// Builds a Rhino Mesh by splitting vertices at UV/normal seams.
        /// OBJ allows a vertex position to have different UVs and normals on
        /// different faces, but Rhino stores UVs and normals per-vertex.
        /// We create a unique vertex for each distinct (position, UV, normal)
        /// combination so that seams render correctly.
        /// </summary>
        private static Mesh BuildRhinoMesh(ParsedMesh parsed, UnitSystem targetUnit)
        {
            double scale = RhinoMath.UnitScale(UnitSystem.Meters, targetUnit);
            bool hasUVs = parsed.TextureCoords.Count > 0;
            bool hasNormals = parsed.Normals.Count > 0;

            var vertexMap = new Dictionary<(int v, int t, int n), int>();
            var positions = new List<Point3d>();
            var uvs = hasUVs ? new List<Point2f>() : null;
            var normals = hasNormals ? new List<Vector3f>() : null;
            var rhinoFaces = new List<(int a, int b, int c, int d)>();

            int ResolveVertex(int vIdx, int tIdx, int nIdx)
            {
                if (vIdx < 0 || vIdx >= parsed.VertexCount) return -1;
                var key = (vIdx, tIdx, nIdx);
                if (vertexMap.TryGetValue(key, out int existing))
                    return existing;

                int newIdx = positions.Count;
                var v = parsed.Vertices[vIdx];
                positions.Add(new Point3d(v.X * scale, v.Y * scale, v.Z * scale));

                if (hasUVs && tIdx >= 0 && tIdx < parsed.TextureCoords.Count)
                {
                    var tc = parsed.TextureCoords[tIdx];
                    uvs.Add(new Point2f((float)tc.X, (float)tc.Y));
                }
                else if (hasUVs)
                {
                    uvs.Add(new Point2f(0, 0));
                }

                if (hasNormals && nIdx >= 0 && nIdx < parsed.Normals.Count)
                {
                    var nm = parsed.Normals[nIdx];
                    normals.Add(new Vector3f((float)nm.X, (float)nm.Y, (float)nm.Z));
                }
                else if (hasNormals)
                {
                    normals.Add(Vector3f.Zero);
                }

                vertexMap[key] = newIdx;
                return newIdx;
            }

            foreach (var f in parsed.Faces)
            {
                int a = ResolveVertex(f.V0, f.T0, f.N0);
                int b = ResolveVertex(f.V1, f.T1, f.N1);
                int c = ResolveVertex(f.V2, f.T2, f.N2);
                if (a < 0 || b < 0 || c < 0) continue;

                if (f.IsQuad)
                {
                    int d = ResolveVertex(f.V3, f.T3, f.N3);
                    if (d < 0) continue;
                    rhinoFaces.Add((a, b, c, d));
                }
                else
                {
                    rhinoFaces.Add((a, b, c, -1));
                }
            }

            var mesh = new Mesh();
            mesh.Vertices.AddVertices(positions);

            foreach (var (a, b, c, d) in rhinoFaces)
            {
                if (d >= 0)
                    mesh.Faces.AddFace(a, b, c, d);
                else
                    mesh.Faces.AddFace(a, b, c);
            }

            if (hasUVs)
                mesh.TextureCoordinates.SetTextureCoordinates(uvs.ToArray());

            if (hasNormals)
                mesh.Normals.SetNormals(normals.ToArray());
            else
                mesh.Normals.ComputeNormals();

            mesh.Compact();
            if (!mesh.IsValid)
                mesh.RebuildNormals();

            return mesh;
        }

        private static string GenerateUniqueBlockName(RhinoDoc doc, string baseName)
        {
            string name = baseName;
            int counter = 1;

            while (doc.InstanceDefinitions.Find(name) != null)
            {
                name = $"{baseName}_{counter}";
                counter++;
            }

            return name;
        }
    }
}
